# Generated by Django 2.2 on 2019-04-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('due', models.DateTimeField()),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in-progress', 'In-progress'), ('done', 'Done')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-due'],
            },
        ),
    ]
